name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.0
  collection: ^1.19.1
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  firebase_auth: ^6.1.2
  google_fonts: ^6.3.3
  freezed_annotation: ^2.4.4
  firebase_core: ^4.2.1
  json_annotation: ^4.9.0
  riverpod_generator: ^3.0.0-dev.11
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
